version: '3.7'

services:
  redis:
    image: angelo87dock/gsweb-redis
    container_name: infra-redis
    networks:
      - lan-network

  rabbitmq:
    image: angelo87dock/gsweb-rabbitmq
    container_name: infra-rabbitmq
    networks:
      - lan-network

  sqlserver:
    image: angelo87dock/gsweb-sqlserver
    container_name: infra-sqlserver
    user: root
    networks:
      - lan-network

  seq-log:
    image: angelo87dock/gsweb-seq
    container_name: infra-seq
    networks:
      - lan-network

networks:
  lan-network:
    external:
      name: docker-net