global:
  scrape_interval:     3s # By default, scrape targets every 5 seconds.

scrape_configs:
  - job_name: 'api-read-prometheus'
    scheme: http
    metrics_path: /metrics
    static_configs:
    - targets:
        - api-gateway:5001
        - api-operazioniavvio:5001
